Alumni name fix
pennlabs/penn-mobile-ios pull request #345
Opened 2020-09-06 12:52 UTC by 01jongmin

Added check to see if the first name is an empty string and if so, just say Howdy!

2020-09-06 18:08 UTC, r3khaan requested changes
Sweet and simple! Before merging in the PR though, I think we should make the experience consistent across users that are not logged in and alumni (see comment above)

2020-09-06 18:08 UTC, r3khaan commented on PennMobile/Home/Controllers/HomeViewController.swift
>                  self.displayTitle = "Home"
I think we should display the same message for users, who are not signed in, & alumni. Both should say "home" or both should give a customized greeting like "howdy." 

I like the latter option more, what do you think?

2020-10-09 07:55 UTC, r3khaan commented
@01jongmin

2020-10-13 17:58 UTC, 01jongmin commented
Apologize for the delay. The code should now follow the later option.

2020-10-14 05:21 UTC, r3khaan requested changes
Very minor change! No need to re-request my review after, feel free to squash and merge yourself.

2020-10-14 09:39 UTC, merged