made the slope average of total + last7
pennlabs/penn-mobile-ios pull request #482
Opened 2023-10-08 17:08 UTC by christinaqiu3

2023-10-09 18:07 UTC, JHawk0224 requested changes
Looks great! I'm a little worried in general though that some people won't like this change. I personally would like it if my predictions kept the slope from the whole semester. Do you think we should add an option somewhere to toggle between these?

On another note, I also personally want to test out the following slope calculation:
For every pair of data points, get the slope between them. Then find the weighted average of all these slopes (based on how many days apart they were from), and use this as the final slope.

2023-10-22 14:16 UTC, joyliu-q commented on PennMobileShared/Dining/DiningAnalyticsViewModel.swift
> +        if slope == 0 {
@JHawk0224 correct me if I'm wrong but I think you can also do:

return slope == 0 ? Date.distantFuture : Calendar.current.date(byAdding: .day, value: Int(offset), to: firstBalance.date)!

2023-10-22 14:16 UTC, joyliu-q commented on PennMobileShared/Dining/DiningAnalyticsViewModel.swift
> +
Some comment documentation about the different methods we use would be great! We're starting to use a variety of methods so clarity becomes important here for future development.

2023-10-22 14:16 UTC, joyliu-q commented on PennMobileShared/Dining/DiningAnalyticsViewModel.swift
> +        if slope == 0 {
Not a swift guru lol but I think it still has the ternary operator syntax

2024-01-21 17:51 UTC, JHawk0224 approved these changes
Looks good, I think it's ready to merge in!

2024-01-21 17:52 UTC, merged